# Generated by Django 5.0.3 on 2024-05-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_profuct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profuct',
            new_name='Product',
        ),
    ]
